/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ContextRouteImport } from './routes/context'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as PluginPluginIdContributionIdRouteImport } from './routes/plugin.$pluginId.$contributionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginPluginIdContributionIdRoute =
  PluginPluginIdContributionIdRouteImport.update({
    id: '/plugin/$pluginId/$contributionId',
    path: '/plugin/$pluginId/$contributionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/plugin/$pluginId/$contributionId': typeof PluginPluginIdContributionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/plugin/$pluginId/$contributionId': typeof PluginPluginIdContributionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/plugin/$pluginId/$contributionId': typeof PluginPluginIdContributionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/plugins'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/skills'
    | '/tools'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/workspace/$id'
    | '/plugin/$pluginId/$contributionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/plugins'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/skills'
    | '/tools'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/workspace/$id'
    | '/plugin/$pluginId/$contributionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/plugins'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/skills'
    | '/tools'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
    | '/workspace/$id'
    | '/plugin/$pluginId/$contributionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ContextRoute: typeof ContextRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  OutputsRoute: typeof OutputsRoute
  PluginsRoute: typeof PluginsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  SignupRoute: typeof SignupRoute
  SkillsRoute: typeof SkillsRoute
  ToolsRoute: typeof ToolsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
  PluginPluginIdContributionIdRoute: typeof PluginPluginIdContributionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin/$pluginId/$contributionId': {
      id: '/plugin/$pluginId/$contributionId'
      path: '/plugin/$pluginId/$contributionId'
      fullPath: '/plugin/$pluginId/$contributionId'
      preLoaderRoute: typeof PluginPluginIdContributionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  BlueprintsRoute: BlueprintsRoute,
  ContextRoute: ContextRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  OutputsRoute: OutputsRoute,
  PluginsRoute: PluginsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  SignupRoute: SignupRoute,
  SkillsRoute: SkillsRoute,
  ToolsRoute: ToolsRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
  PluginPluginIdContributionIdRoute: PluginPluginIdContributionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
